"""empty message

Revision ID: 0defc1772a1d
Revises: 2eaed332f5d6
Create Date: 2024-10-12 19:50:23.619447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0defc1772a1d'
down_revision = '2eaed332f5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appearances', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appearances', 'guest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appearances', 'guest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appearances', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
